### ISSUE TITLE
软件问题

### ISSUE THREAD

**Issue by LeoYanlv** [ghanthony/rightKeyCustomSearch#5]
1、没有内置规则
2、鼠标只能在浮窗里面，一点外面就退出
3、保存还要手动
1+2+3真是配合的完美，开2个窗口从【使用帮助】复制规则到【搜索列表】，鼠标一全选选到外面去了，重来，鼠标点到外面去了，重来，忘记点保存，重来。。。
4、帮助里面豆瓣规则是错的
5、一级菜单名字不能改“自定义右键搜索”

**Comment by ghanthony** [comment]
> 1、没有内置规则
> 2、鼠标只能在浮窗里面，一点外面就退出
> 3、保存还要手动
> 1+2+3真是配合的完美，开2个窗口从【使用帮助】复制规则到【搜索列表】，鼠标一全选选到外面去了，重来，鼠标点到外面去了，重来，忘记点保存，重来。。。
> 4、帮助里面豆瓣规则是错的
> 5、一级菜单名字不能改“自定义右键搜索”

1.没有，给了参考规则，可以结合自己的使用习惯进行配置
2.是的，编辑好之后点击确定就行
3.是的
4.豆瓣或者其他网站会更新自己的搜索url，失效后修改即刻
5.没有考虑需要更换一级菜单名字的需求
